import { useState } from "react";
import Card from "../components/ui/Card";
import Badge from "../components/ui/Badge";
import Button from "../components/ui/Button";
import SectionHeading from "../components/ui/SectionHeading";

type ChatMessage = {
  id: number;
  role: "student" | "mentor";
  text: string;
};

const initialMessages: ChatMessage[] = [
  {
    id: 1,
    role: "mentor",
    text: "AI Mentor is being prepared for the simulation phase. Once experiments are connected to real simulation data, I'll be able to explain your results here.",
  },
];

function MentorPage() {
  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [draft, setDraft] = useState("");

  function handleSend() {
    const trimmed = draft.trim();
    if (!trimmed) {
      return;
    }

    const studentMessage: ChatMessage = {
      id: messages.length + 1,
      role: "student",
      text: trimmed,
    };

    const mentorReply: ChatMessage = {
      id: messages.length + 2,
      role: "mentor",
      text: "The AI Mentor isn't connected yet. This message has been recorded in the UI only.",
    };

    setMessages([...messages, studentMessage, mentorReply]);
    setDraft("");
  }

  return (
    <div className="placeholder-page mentor-page">
      <SectionHeading
        eyebrow="AI Mentor"
        title="Your guide through every experiment"
        description="Ask questions about an experiment and get contextual explanations, once the simulation engine is connected."
      />

      <Card className="mentor-status-card">
        <Badge variant="warning">Coming in Phase 2</Badge>
        <p>
          The Mentor chat below is a working interface, but responses are
          not generated by a real AI model yet. This UI is ready for the
          simulation and AI services described in the architecture docs.
        </p>
      </Card>

      <Card className="mentor-chat-card">
        <div className="mentor-chat-context">
          <span className="eyebrow">Experiment context</span>
          <p>No experiment selected. Open an experiment to bring its context here.</p>
        </div>

        <div className="mentor-chat-messages">
          {messages.map((message) => (
            <div key={message.id} className={`mentor-message mentor-message-${message.role}`}>
              <span className="mentor-message-role">
                {message.role === "mentor" ? "Mentor" : "You"}
              </span>
              <p>{message.text}</p>
            </div>
          ))}
        </div>

        <div className="mentor-chat-input">
          <input
            type="text"
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                handleSend();
              }
            }}
            placeholder="Ask the mentor about this experiment..."
          />
          <Button onClick={handleSend}>Send</Button>
        </div>
      </Card>
    </div>
  );
}

export default MentorPage;
